//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudAgroCauca.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CanastaProducto
    {
        public int Id { get; set; }
        public string NombreProducto { get; set; }
        public string ImagenProducto { get; set; }
        public string CantidadProdcto { get; set; }
        public string PrecioProducto { get; set; }
        public string DescuentoProducto { get; set; }
    }
}
